# Generated by Django 3.1.7 on 2023-08-24 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories_upload', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memory',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners_upload', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
