# Generated by Django 3.1.7 on 2023-08-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20230824_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
