# Generated by Django 3.1.7 on 2023-08-24 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='comments',
            field=models.ManyToManyField(related_name='commented_memories', through='memories.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memory',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='memories_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memory',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memories.memory'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_memories', to=settings.AUTH_USER_MODEL),
        ),
    ]
